export enum ContainerStatusEnum {
  CONTAINER_STATUS_STARTED = 0,
  CONTAINER_STATUS_STOPPED = 1,
  CONTAINER_STATUS_EXITED = 2,
  CONTAINER_STATUS_STARTING = 3,
  CONTAINER_STATUS_STOPPING = 4,
  CONTAINER_STATUS_COULD_NOT_STOP = 5,
  CONTAINER_STATUS_COULD_NOT_START = 6,
}
